### ISSUE TITLE
[WIP] Turnip supports Ruby 2.0.0+ (remove 1.9.3)

### ISSUE THREAD

**Issue by gongo** [jnicklas/turnip#150]
I think should remove support for Ruby 1.9.3.
Because, Ruby 1.9.3 is EOL since 23 Feb 2015 (See: [Support for Ruby 1.9.3 has ended](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/))

@jnicklas Do you think about it?

**Comment by gongo** [comment]
For now, I will not do big changes. I plan to fix the following codes:

- [travis.yml](https://github.com/jnicklas/turnip/blob/49a13357e5722057d2c4bd4689bb859c59fa2c7f/.travis.yml#L6)
- [1.9.2 support hack on builder.rb](https://github.com/jnicklas/turnip/blob/49a13357e5722057d2c4bd4689bb859c59fa2c7f/lib/turnip/builder.rb#L113-L117)

**Comment by jnicklas** [comment]
Yes! In my opinion, EOL'd Rubies should not be supported.

**Comment by gongo** [comment]
Thank you for reply!

**Comment by gongo** [comment]
This issue was finished GH-151
