### ISSUE TITLE
Should/should not style steps

### ISSUE THREAD

**Issue by YaroSpace** [jnicklas/turnip#152]
Guys, am I missing something trivial here?  
How do I dry out very similar steps with opposite expectations like `I should see :text` and `I should not see :text`?  
In Cucumber it is done with regex and optional arguments.  Is there a way in Turnip?

**Comment by gongo** [comment]
Similar question here. Please check it. 
[How to change alternative words from cucumber to turnip? - Google Groups](https://groups.google.com/forum/#!searchin/ruby-turnip/should$20not/ruby-turnip/cvs_8FLTWKU/zrKCoH4DO2QJ)

Other way, use `placeholder`:

```ruby
placeholder :positive do
  match /should not/ do |m|
    false
  end

  match /should/ do |m|
    true
  end
end
```

Example:

```ruby
step 'I :positive see :text' do |positive, text|
  if positive
    # expect(text).to ...
  else
    # expect(text).not_to ...
  end
end
```

```feature
Feature: Should/ShouldNot Test
  Scenario: Should
    Given I should see "foo"

  Scenario: Should not
    Given I should not see "bar"
```

**Comment by YaroSpace** [comment]
Wow, @gongo,  thank you so much for this.  I never realized that placeholders can include more than word separated by spaces.  This deserves to go to Readme.

**Comment by gongo** [comment]
> This deserves to go to Readme.

I'll consider it. Or we will wait for the PR!

**Comment by YaroSpace** [comment]
Alright, let me do that...
