### ISSUE TITLE
[Proposal] RSpec support policy

### ISSUE THREAD

**Issue by gongo** [jnicklas/turnip#158]
## Motivation

Now, `jnicklas/turnip` supports multiple version of RSpec (See: [.travis.yml](https://github.com/jnicklas/turnip/blob/v1.3.1/.travis.yml#L21-L27)):

- RSpec 2.14.x
- RSpec 2.99.x
- RSpec 3.0.x
- RSpec 3.1.x
- RSpec 3.2.x
- RSpec 3.3.x

I think there are too many.

## Proposed changes for support version

Ideally, **latest version only**.

But, I think everyone is not able to use the latest version.
And, many developers are using `2.14.x` yet (maybe..).

Therefore, We propose the following policy:

- Latest version
- Previous version
- 2.14.x version

Example: 

1. RSpec 3.3.x
1. RSpec 3.2.x
1. RSpec 2.14.x

## In the future

When `RSpec 4` was released, will stop support for `RSpec 2.14.x`.

**Comment by a-suenami** [comment]
LGTM :meat_on_bone:

**Comment by KazuCocoa** [comment]
I vote your your proposal, Latest version, Previous version and 2.14.x version.
It is enough in most cases, i suppose.

**Comment by PragTob** [comment]
Keeping compatibility with many versions is difficult. People still using Rspec 2.14 can also keep using an older version of turnip which supports 2.14 imo. :) 

E.g. if it were up to me I'd drop support for 2.x and make a new major release. And then only support 3.x or even 3.2+

**Comment by gongo** [comment]
> E.g. if it were up to me I'd drop support for 2.x and make a new major release. And then only support 3.x or even 3.2+

E.g.

- turnip 1.3.x -> RSpec 3.x, RSpec 2.x
- turnip 1.4.x (or 2.x) -> RSpec 3.x only

**Comment by PragTob** [comment]
Make it 2.x as dropping support for a version is considered breaking and hence justifies a major version bump in semver. Good time to maybe make some other breaking changes :)

Thank you btw. for maintaining, I love turnip and over time feared it had gone unmaintained. Good to see that this is not the case :+1:

**Comment by lukaso** [comment]
While we're talking breaking changes, we'd love to get our rutabaga gem incorporated... It allows you to call features straight out of rspec (inverts the control). https://github.com/simplybusiness/rutabaga. Rutabaga is a lot closer to how CucumberJVM works, I think.

**Comment by gongo** [comment]
Hi @lukaso 

> we'd love to get our rutabaga gem incorporated..

What's mean? "Rutabaga feature is provided as a built-in of Turnip" ?

**Comment by PragTob** [comment]
@lukaso I believe this should rather be discussed in a separate issue :) Aside from that I believe that extra gems for extra/changed functionality are a good thing :)

**Comment by lukaso** [comment]
Agreed as separate issue: #159

**Comment by gongo** [comment]
Thank you for comment :pizza: 
I decided to RSpec support policy and major release plan.

---

When **RSpec 3.4.0** is released,  I will release **Turnip 2.0.0**.
Turnip 2.0.0 or later:

- Not support RSpec 2.x
- Support RSpec 3.x latest version and previous version
    - ex. `RSpec 3.4.x + RSpec 3.3.x`, `RSpec 3.5.x + RSpec 3.4.x`

If want to use RSpec 2, please use `Turnip 1.3.x`

**Comment by PragTob** [comment]
:+1:

**Comment by gongo** [comment]
I created https://github.com/jnicklas/turnip/tree/2_0_0_rc1 :smile:

**Comment by gongo** [comment]
RSpec 3.4.0 was released :tada:
https://github.com/rspec/rspec-core/releases/tag/v3.4.0
