### ISSUE TITLE
Export features in cucumber json format

### ISSUE THREAD

**Issue by JohnBat26** [jnicklas/turnip#162]
Hello.
How can I export features in cucumber json format for use with https://github.com/picklesdoc/pickles ?

**Comment by gongo** [comment]
Turnip does not have export in cucumber json format.

**Comment by JohnBat26** [comment]
Hmm. I would be very usefull for live documentation and export in doc and excel documents

**Comment by gongo** [comment]
I think so too :smile:

**Comment by JohnKacz** [comment]
So is this even a possibility for the future? If so, shouldn't this be left open as a feature request?

**Comment by gongo** [comment]
In the future, I'd like to implement in https://github.com/gongo/turnip_formatter

**Comment by JohnKacz** [comment]
@gongo Thanks for the link!
