### ISSUE TITLE
Background Steps are Not Displayed in Output

### ISSUE THREAD

**Issue by jnyman** [jnicklas/turnip#166]
Say I have this feature file:

    Feature: Support test specs with a background

      Background:
        Given a hostile NPC

      Scenario:
        When the NPC is attacked with a basic attack
        Then the NPC will be defeated

Assuming code is place for the steps, everything runs just fine but the output looks like this:

    Support test specs with a background

        When the NPC is attacked with a basic attack -> Then the NPC will be defeated

The background portion of the test is not printed. I looked and didn't see anything in the documentation that would suggest this was done deliberately.

The reason I treat this as a bug is because part of having the output readable by anyone is to make sure they understand the full context of the execution. It seems that by leaving out the background, this is removing a key piece of information.

**Comment by gongo** [comment]
Hi @jnyman 

You are right! I will fix it soon.

**Comment by gongo** [comment]
@jnyman 

I've released [v2.0.1](https://github.com/jnicklas/turnip/releases/tag/v2.0.1) . Please check it!

**Comment by jnyman** [comment]
Indeed I have tested this out with the new version and it looks to be working just fine. I now see the background step output with the rest of the steps.
