### ISSUE TITLE
place upper bound on gherkin dependency

### ISSUE THREAD

**Issue by munkyboy** [jnicklas/turnip#169]
https://github.com/cucumber/gherkin just released version 3.2 of their gem. The gem is now published as `gherkin` whereas before I think it was published as `gherkin3`. It seems turnip is not compatible with the v3 line of `gherkin`. I suggest limiting the dependency to the 2.x line.

**Comment by gongo** [comment]
Hi @munkyboy 

Thanks for report!
I will lock `gherkin ~>2.5` soon.

**Comment by gongo** [comment]
@munkyboy 

I've released `turnip-2.0.2` that lock gherkin version to `2.x`

**Comment by munkyboy** [comment]
awesome. thanks for the prompt response!
