### ISSUE TITLE
How to use alternative words in step written in Japanese? (no spaces between words)

### ISSUE THREAD

**Issue by hanachin** [jnicklas/turnip#175]
I want to write the step like following:

```rb
step "〜の中に/の○○" do |innner_step|
  # 〜
end
# expect it matches "〜の中に○○" and "〜の中の○○" steps
```

but turnip compiles that to something like following regexp:

```rb
/(〜の中に|の)○○/
```

I know wrap alternative words with optional parts parences would work, but it match step without に/の.

```rb
step "〜の中(に/の)○○" do |innner_step|
  # 〜
end
# it matches the step like:
# 〜の中○○
```

Here is my work around:

```rb
step "〜の中( )に/の( )○○" do |innner_step|
end
# it matches "〜の中に○○" and "〜の中の○○" steps, also match "〜の中 に ○○", "〜の中 の ○○"
```

**Comment by gongo** [comment]
Hi @hanachin 



> I know wrap alternative words with optional parts parences would work, but it match step without に/の.
> 
> ```
> step "〜の中(に/の)○○" do |innner_step|
>   # 〜
> end
> # it matches the step like:
> # 〜の中○○
> ```

Hmm.. it ran as expected when I try.
(sample codes: https://gist.github.com/gongo/00e21949dd62c591e45d)

**Comment by gongo** [comment]
Oh.

> ```
> # it matches the step like:
> # 〜の中○○
> ```

means

```
    And ポケットの中の戦争      # <= match OK
    And ポケットの中にビスケット # <= match OK
    And ポケットの中ガンダム    # <= match but not expect
```

?

**Comment by hanachin** [comment]
@gongo はい。(慣れない英語で言葉たらずですみません)

**Comment by gongo** [comment]
@hanachin 

Umm... sorry, it is difficult to specify alternative words to text not leaving a space between words (= 分かち書き).

- `〜の中に/の`  can be divided as follows:
    - `〜の中` `に/の`
    - `〜の` `中に/の`
    - `〜` `の中に/の` 

`turnip` don't know the correct.

And, `(に/の)` syntax is recognized as **optional parts** https://github.com/jnicklas/turnip#placeholders

- `〜の中の`
- `〜の中に`
- `〜の中`

Correct all!

---

(Japanese!!)

なので、現状は workaround をそのまま続けていただくか、
助詞が無い場合もマッチしてしまう可能性は残っていますが
そこそこ見易い `(の/に)` という書き方でカバーしていただけますか。

**Comment by hanachin** [comment]
thank you for quick response!
 
ありがとうございます :pizza:
