### ISSUE TITLE
Cucumber like reporter

### ISSUE THREAD

**Issue by leoc** [jnicklas/turnip#180]
Is there a reporter that can export a cucumber-like list of features & scenarios?

Ideally, I want to export an HTML report for my customers that shows all features, scenarios & steps and whether they passed or not.

This should only be done for the features, not the other specs.

Could you give me a tip, on how you would start? :+1:  Thank you!

**Comment by gongo** [comment]
Hi @leoc 

There is [turnip_formatter](https://github.com/gongo/turnip_formatter) that can export a HTML (example: [here](https://github.com/gongo/turnip_formatter/tree/master/example)) 
(This is an unofficial gem 😄)

Please try!

Thanks

**Comment by leoc** [comment]
Thanks! That one completely slipped by me. I will try it!
