### ISSUE TITLE
require': cannot load such file -- gherkin (LoadError)

### ISSUE THREAD

**Issue by newmizanur** [jnicklas/turnip#189]
Cannot run rspec getting gherkin (LoadError)
I'm trying to run rspec but getting load error which raising like bellow. Done gem install gherkin, gem install cucumber and added -r turnip/rspec to .rspec but not worked.

`.rvm/gems/ruby-2.0.0-p648/gems/turnip-1.3.1/lib/turnip/builder.rb:1:in `require': cannot load such file -- gherkin (LoadError)
        from /home/mizan/.rvm/gems/ruby-2.0.0-p648/gems/turnip-1.3.1/lib/turnip/builder.rb:1:in `<top (required)>'
`

**Comment by gongo** [comment]
Hi @newmizanur 

1. What version of `gherkin` did you install? `turnip-1.3.1` only works in `gherkin 2.x` .
2. `turnip-1.3.1` is very old. Please use one of the following:
    - ver 3.x (beta)
    - ver 2.1.1 (current stable)
    - ver 2.0.2 (support to Ruby 2.0)

**Comment by newmizanur** [comment]
Thanks turnip 1.3.1 worked gherkin 2.5 !
