### ISSUE TITLE
Feature request: indicating incomplete/pending step definitions?

### ISSUE THREAD

**Issue by rlue** [jnicklas/turnip#198]
RSpec offers a feature wherein [examples or example groups may be labelled "pending" by not providing a block, or by prepending an `x` to the name of the corresponding method](https://relishapp.com/rspec/rspec-core/v/3-7/docs/pending-and-skipped-examples/pending-examples) (_e.g.,_ `xit` vs. `it` or `xdescribe` vs. `describe`).

Currently, features are skipped and labelled "pending" if the step definition is not found, but if it's present with no block given, the example fails. Any chance we could get no-block-given (and a corresponding `xstep` method) to make the example pending?

**Comment by gongo** [comment]
Hi @rlue 

Could you substitute `xstep` by the following codes?

Feature file:

```feature
Feature: feature
  Scenario: scenario
    Given Instead of xstep
```

Step file:

```rb
step 'Instead of xstep' do
  skip
end
```

Execution:

```sh-session
$ rspec foo.feature

*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) feature scenario Given Instead of xstep
     # No reason given
     # ./foo.feature:2

Finished in 0.00465 seconds (files took 0.17566 seconds to load)
1 example, 0 failures, 1 pending
```

**Comment by rlue** [comment]
Ah, `skip` does work. 

Still, it would be nice to have this syntax available, merely in the interest of consistency with RSpec. I'd be willing to work on a PR for it when I have some time, if the team is open to the idea.

Would that be alright?

**Comment by gongo** [comment]
Umm.

I'm negative to implement `xstep()` and `no-block-given step()` as official Turnip DSL.
Especially, I think the `xstep` is easy to make mistakes.

```ruby
step 'foo' do
   # ...
end

xstep 'bar' do # `x` is hard to notice
   # ...
end

step 'baz' do
  skip # It is easy to notice that this step skip.
end
```

**Comment by rlue** [comment]
You're the boss!

> Umm.

FYI, this sounds a little rude (to me). I'm sure you didn't mean it that way. Here is my analysis of what you might have meant:

* > **Hm.**
  >
  > I'm negative to...

  This says, "That's interesting; let me consider that for a moment" before you get into your opinion.

* > **Um,** I'm negative to...

  This also works. It allows you to say what you want to, but it suggests you are a little reluctant or uncomfortable saying it, maybe because you don't want to hurt someone else's feelings. 

* > **Um.**
  >
  > I'm negative to...

  This means, "I am dumbstruck by what you just said" (as in, I disagree so much that I don't know what to say).

  When I see "Um." (or "Um...") on its own line like that, this is the face I imagine:

  ![screen shot 2018-01-19 at 4 54 38 pm](https://user-images.githubusercontent.com/12194123/35142518-853c0d16-fd39-11e7-9188-d46cdcd3566a.png)

But of course, feel free to let me know if that's what you really meant. ;)

**Comment by rlue** [comment]
Don't mention it! :)

> Sorry for making you feel uncomfortable. 

That's okay. Programmers don't have feelings.
