### ISSUE TITLE
Support for gherkin 5.0.0 coming?

### ISSUE THREAD

**Issue by mileslane** [jnicklas/turnip#199]
bundle outdated reports:
gherkin (newest 5.0.0, installed 4.1.3)

And Gemfile.lock contains:

turnip (3.0.0)
       gherkin (~> 4.0)

**Comment by gongo** [comment]
Hi @mileslane .

> Support for gherkin 5.0.0 coming?

Yes! (someday soon)

**Comment by gongo** [comment]
I've released 3.1.0 that support gherkin 5.0 https://github.com/jnicklas/turnip/releases/tag/v3.1.0
