### ISSUE TITLE
Turnip and Rails 5.1+ system tests

### ISSUE THREAD

**Issue by tammersaleh** [jnicklas/turnip#233]
I've read that Rails 6 implements some nice features (like DB connection sharing) for "system" tests, which allows us to remove the `database_cleaner` gem and use normal DB transactions when testing with Capybara against headless chrome.  

I _think_ the way to enable that in rspec is to set the spec `:type => :system`.  It looks like Turnip features are `:type=> :feature`.  Is there a way to change that to `:system` and get the nice Rails system test features?  Maybe it's not necessary?

**Comment by hanachin** [comment]
I added this setting to `spec/turnip_helper.rb`
```ruby
Turnip.type = :system
```
