### ISSUE TITLE
Feature files are not loaded with rake spec

### ISSUE THREAD

**Issue by gravis** [jnicklas/turnip#79]
In the README, it's said :

"It will automatically be run if you run all your specs with rake spec or rspec spec."

That's not the case for me, `.feature` files are not loaded in the suite when I use `rake`, or `rake spec`

thanks

**Comment by fernandes** [comment]
@gravis your solution helped me on running turnip specs on travis (using default rake task) thank you!

**Comment by skinofstars** [comment]
:+1: on @gravis solution for making plain old `rake` work
